config/routes.rb
Rails.application.routes.draw do
  resources :pdfs
  post 'pdfs/generate_pdf'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pdf.rb
class Pdf < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  before_action :set_pdf, only: %i[ show edit update destroy ]

  # GET /pdfs or /pdfs.json
  def index
    @pdfs = Pdf.all
    @filepath = Rails.root.join('public' ,'uploads' , 'file.pdf').to_s
  end

g

  def generate_pdf
    require 'pdfkit'
    kit = PDFKit.new('<h1>Hello haris</h1>')
    pdf = kit.to_pdf
    filepath =  Rails.root.join('public', 'uploads' , 'file.pdf').to_s
    file = kit.to_file(filepath)
  end




  # GET /pdfs/1 or /pdfs/1.json
  def show
  end

  # GET /pdfs/new
  def new
    @pdf = Pdf.new
  end

  # GET /pdfs/1/edit
  def edit
  end

  # POST /pdfs or /pdfs.json
  def create
    @pdf = Pdf.new(pdf_params)

    respond_to do |format|
      if @pdf.save
        format.html { redirect_to pdf_url(@pdf), notice: "Pdf was successfully created." }
        format.json { render :show, status: :created, location: @pdf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pdfs/1 or /pdfs/1.json
  def update
    respond_to do |format|
      if @pdf.update(pdf_params)
        format.html { redirect_to pdf_url(@pdf), notice: "Pdf was successfully updated." }
        format.json { render :show, status: :ok, location: @pdf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pdf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdfs/1 or /pdfs/1.json
  def destroy
    @pdf.destroy

    respond_to do |format|
      format.html { redirect_to pdfs_url, notice: "Pdf was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdf
      @pdf = Pdf.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pdf_params
      params.require(:pdf).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdfkitSec</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pdfs/_form.html.erb
<%= form_with(model: pdf) do |form| %>
  <% if pdf.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pdf.errors.count, "error") %> prohibited this pdf from being saved:</h2>

      <ul>
        <% pdf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pdfs/_pdf.html.erb
<div id="<%= dom_id pdf %>">
  <p>
    <strong>Name:</strong>
    <%= pdf.name %>
  </p>

</div>

app/views/pdfs/edit.html.erb
<h1>Editing pdf</h1>

<%= render "form", pdf: @pdf %>

<br>

<div>
  <%= link_to "Show this pdf", @pdf %> |
  <%= link_to "Back to pdfs", pdfs_path %>
</div>

app/views/pdfs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pdfs</h1>

<%= button_to "Generate Pdf" , pdfs_generate_pdf_path %> <br><br>
<a href="/uploads/file.pdf" download="file.pdf">Download PDF in html</a><br>
<%= link_to 'Download PDF rails', '/uploads/file.pdf', download: 'file.pdf' %><br>




<div id="pdfs">
  <% @pdfs.each do |pdf| %>
    <%= render pdf %>
    <p>
      <%= link_to "Show this pdf", pdf %>
    </p>
  <% end %>
</div>

<%= link_to "New pdf", new_pdf_path %>

app/views/pdfs/new.html.erb
<h1>New pdf</h1>

<%= render "form", pdf: @pdf %>

<br>

<div>
  <%= link_to "Back to pdfs", pdfs_path %>
</div>

app/views/pdfs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pdf %>

<div>
  <%= link_to "Edit this pdf", edit_pdf_path(@pdf) %> |
  <%= link_to "Back to pdfs", pdfs_path %>

  <%= button_to "Destroy this pdf", @pdf, method: :delete %>
</div>

app/views/pdfs/template.html.erb
<html>
<h1>Hello Haris</h1>
</html>